spring.application.name=springsecuritydbconnection

spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5433/springboot
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=env,beans